# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from __future__ import unicode_literals
from ..dsi_studio import Tracking


def test_Tracking_inputs():
    input_map = dict(
        args=dict(argstr='%s', ),
        connectivity=dict(argstr='--connectivity=%s', ),
        connectivity_type=dict(argstr='--connectivity_type=%s', ),
        connectivity_value=dict(argstr='--connectivity_value=%s', ),
        end=dict(argstr='--end=%s', ),
        end2=dict(argstr='--end2=%s', ),
        environ=dict(
            nohash=True,
            usedefault=True,
        ),
        fa_threshold=dict(argstr='--fa_threshold=%.2f', ),
        fiber_count=dict(
            argstr='--fiber_count=%d',
            xor=['seed_count'],
        ),
        ignore_exception=dict(
            deprecated='1.0.0',
            nohash=True,
            usedefault=True,
        ),
        initial_dir=dict(argstr='--initial_dir=%d', ),
        input_fib=dict(
            argstr='--source=%s',
            copyfile=False,
            mandatory=True,
        ),
        interpo_angle=dict(argstr='--interpo_angle=%.2f', ),
        interpolation=dict(argstr='--interpolation=%d', ),
        max_length=dict(argstr='--max_length=%d', ),
        method=dict(
            argstr='--method=%d',
            usedefault=True,
        ),
        min_length=dict(argstr='--min_length=%d', ),
        output_trk=dict(
            argstr='--output=%s',
            name_source='input_fib',
            name_template='%s.trk.gz',
        ),
        random_seed=dict(argstr='--random_seed=1', ),
        roa=dict(argstr='--roa=%s', ),
        roi=dict(argstr='--roi=%s', ),
        roi2=dict(argstr='--roi2=%s', ),
        seed_count=dict(
            argstr='--seed_count=%d',
            xor=['fiber_count'],
        ),
        seed_file=dict(argstr='--seed=%s', ),
        seed_plan=dict(argstr='--seed_plan=%d', ),
        smoothing=dict(argstr='--smoothing=%.2f', ),
        step_size=dict(argstr='--step_size=%.2f', ),
        ter=dict(argstr='--ter=%s', ),
        terminal_output=dict(
            deprecated='1.0.0',
            nohash=True,
        ),
        thread_count=dict(
            argstr='--thread_count=%d',
            usedefault=True,
        ),
        to_export=dict(argstr='--export=%s', ),
        tract_file=dict(argstr='--tract=%s', ),
        turning_angle=dict(argstr='--turning_angle=%.2f', ),
    )
    inputs = Tracking.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value
def test_Tracking_outputs():
    output_map = dict(
        connectivity_matrices=dict(),
        output_gfa=dict(),
        output_qa=dict(),
        output_trk=dict(
            argstr='--output=%s',
            name_source='input_fib',
            name_template='%s.trk.gz',
        ),
    )
    outputs = Tracking.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
